### ISSUE TITLE
Urgency support

### ISSUE THREAD

**Issue by jaxxstorm** [jaxxstorm/redphone#10]
Pagerduty recently announced support for "urgencies" for the incidents: 

https://www.pagerduty.com/blog/incident-analytics-urgencies/

When their API is updated, we should take advantage of that.

**Comment by jaxxstorm** [comment]
@portertech are you still maintaining this?

**Comment by portertech** [comment]
@jaxxstorm I began the repo transfer process :+1: what's your rubygems profile?

**Comment by jaxxstorm** [comment]
Closing, this isn't supported on a per incident basis, only a per-schedule basis after discussion with pagerduty support
